include ../_dkm/*

## Variables
# Static
REGISTRY_REMOTE=docker.io
NAMESPACE=jfrog
CONTAINER=registry
TAG=2
CONTAINER_HOME=/var/lib/registry


#docker run -d -p 52095:5000 --restart=always --name docker-registry \
#  -v /data/docker-registry:/var/lib/registry \
#  registry:2
