include ../../_dkm/*

## Variables
# Static
REGISTRY_REMOTE=jfrog-docker-registry.bintray.io
NAMESPACE=jfrog
CONTAINER=artifactory-oss
TAG=latest
CONTAINER_HOME=/var/opt/jfrog/artifactory
CONTAINER_PORT=8081
